### ISSUE TITLE
Thread safety of Ix-Async in general

### ISSUE THREAD

**Issue by danielcweber** [Reactive-Extensions/Rx.NET#145]
I'm no expert in the .net memory model and have adhered to the pretty conservative principle of having locks around accesses to shared variables (even on reads - as Eric Lippert suggests [here](http://blog.coverity.com/2014/03/12/can-skip-lock-reading-integer/)). Not so much because of possible race conditions but because of the odd things that may happen in multithreaded code wrt. possible reorderings of reads and writes.

So, I'm somewhat puzzled about the assumptions that are made throughout the Ix-Async library. A common pattern in many Ix-Async operator implementations is to have the current value (of an IAsyncEnumerator) stored within a variable without any locks. Access to the shared variable is not synchronized (check [this](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Single.cs#L38) and [this](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Ix.NET/Source/System.Interactive.Async/AsyncEnumerable.Single.cs#L57) as an example). Reads and writes to `current` must be expected to happen on different threads, however, there are no locks. If you read anything about the .net memory model and possible read- and write-reorderings, the conclusion is always that almost all bets are off without locks. So what assumptions make this code work so well in practice? Am I missing something?

**Comment by buybackoff** [comment]
Crossing async/await barrier implicitly generates full fences: http://www.albahari.com/threading/part4.aspx#_Memory_Barriers_and_Volatility
http://blogs.msdn.com/b/pfxteam/archive/2012/04/12/async-await-faq.aspx

If a thread A calls `MoveNextAsync()` it awaits for the returned Tasks and accesses the `Current` property only after the task is complete (a write to the `Current` is done on some thread B in a thread pool, but before the task returns).

If you access `Current` from A before `MoveNextAsync()` returns, the thread B could write to the `Current` just before returning and you could get a new value. Here you actually do want to get previous value, because by the contract of I(Async)Enumerable, `Current` could be called many times after MoveNext(Async) returns `true`. BUT! This is not possible, because the caller that have already called `MoveNextAsync()` could not access `Current` while it is awaiting on `MoveNextAsync()`. You have to introduce a third thread (two parallel consumers of a single enumerator), but as far as I understand, I(Async)Enumerator should be used only from a single thread, being `async` doesn't make it thread-safe, but just allows for non-blocking behavior.
