### ISSUE TITLE
SubjectBase

### ISSUE THREAD

**Issue by grokys** [Reactive-Extensions/Rx.NET#158]
I notice that `SubjectBase` has been added (though it's not yet available in any release) however it only defines abstract methods, which is kinda useless. It would be good if it also handled the low-level plumbing with `ImmutableList` etc.

**Comment by grokys** [comment]
Especially as Rx's ImmutableList is internal, so we either need to take a dependency on Immutable Collections, or copy Rx's ImmutableList into our code.

**Comment by shiftkey** [comment]
@grokys is this still something you're interested in?

**Comment by grokys** [comment]
Yeah, it's definitely something that would be useful!

**Comment by shiftkey** [comment]
@grokys ok cool, let's tease this stuff out:

 - what would you like to see changed with `SubjectBase`? For reference, it's mostly being used as a base class, and I get the feeling that's why it's necessary to make public:

<img width="544" src="https://cloud.githubusercontent.com/assets/359239/16738682/a25778a4-474b-11e6-9351-30e414bd9c7e.png">

 - do you think we should adopt `ImmutableList` internally and remove that code? That feels better for the overall ecosystem, rather than making Yet Another Implementation public and encouraging more fragmentation...

**Comment by shiftkey** [comment]
[Here's a rough PR which migrates our usage of the internal `ImmutableList` over to use the `System.Collections.Immutable` version](https://github.com/Reactive-Extensions/Rx.NET/compare/master...shiftkey:be-more-immutable?expand=1) - much easier than I anticipated...

**Comment by onovotny** [comment]
Definitely a 👍 to using the external ImmutableList now and removing our impl now that we can.

**Comment by flagbug** [comment]
We have to be careful with swapping those, see https://github.com/Reactive-Extensions/Rx.NET/pull/222#issuecomment-231825104

**Comment by grokys** [comment]
Ok, it seems that the use-case I was thinking of when I created this issue is no longer relevant, but I can explain what I was thinking:

The problem was that the `ImmutableList` impl in Rx was private so that to create my own subject I would've had to add a new dependency that I didn't previously have. Moving to `System.Collections.Immutable` would of course make that no longer true.

However, there's a lot of commonality to the implementations of `OnNext`/`OnError`/`OnCompleted` in the different subject implementations, which could maybe be exposed, but I think the recently added `Subject.Create` method should make creating a new new subject less common; so probably not worth messing with this.

Closing this for now.
