### ISSUE TITLE
Rx through network

### ISSUE THREAD

**Issue by jfferland** [Reactive-Extensions/Rx.NET#240]
There's any development planned to integrate a network version of Rx such as the one proposed by Dave Sexton? [(https://github.com/RxDave/Qactive)](url)

I've been using the old version Rxx he published( [(https://github.com/RxDave/Qactive)](url) ) for 1 year and half, it's great and simplify coding so much. Would be great enhancement to Rx.

**Comment by shiftkey** [comment]
I think this also overlaps with the [Rx + Cortana](https://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Rx-and-Cortana) stuff that @bartdesmet has been working on for a while.

I'm not sure how this all fits into the big picture, and am definitely _not_ the person to decide...

**Comment by RxDave** [comment]
It probably overlaps, but that shouldn't matter. I published it because I needed it now to solve critical memory/performance problems in a project that I'm working on for a bank, and I couldn't wait any longer for Microsoft to release theirs. But when they do, we'll be considering switching to it. I'm still really excited by the prospect of being able to use an "official", open source, distributed Rx query engine!

There's a lot that's different too probably. For example, we have specific technical constraints in our project, and Qactive solves our problems nicely due to the fact that it has no additional environment/platform/library dependencies, just vanilla Rx itself. We're not using any message queueing or making any reliability guarantees either, because we simply don't need it -- if there's a disconnect, we simply resubmit the entire query without attempting to reload any previous state. And we're only using C# on both sides, at the moment, so our serialization and programming models are simple; however, soon we're going to need support for HTML5 / JS clients as well (unfortunately :-P), so I'm currently working on updates for Qactive: WebSockets and C# script queries. This requirements also keeps me interested in Microsoft's implementation of the so-called "bonsai trees". To use their entire platform though, it seems that we may require a light-weight version that avoids any external dependencies (such as Azure), so we may end up relying on Qactive for the long haul anyway.

**Comment by jfferland** [comment]
Sry for the delay, couldn't reply as quick as you two. Really appreciated the quick replies.

@shiftkey Thanks for the videos, I have watched a couple more and it gives enough hope for an official release soon or later.
@RxDave You're right, it may overlaps, but you did a genius implementation that take our software to the next level that we wouldn't easily reached without your current implementation of the Rx remote library. Keep that great job Dave, it's a very valuable work for the community.
