### ISSUE TITLE
Integration with event where the delegate has more than one argument and there are no EventArgs

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#243]
There appears to be no overload of the `FromEvent` or `FromEventPattern` methods that will convert into an `IObservable<T>` an event with the type `TDelegate` only where there is more than one parameter and there is no `EventArgs`.

For e.g. it appears that we cannot convert the following into observables.

    public event Action<int, int> SomethingHappened;
    
    public event Func<string, int> SomethingElseHappened;

We either *have to have* an `EventArgs` in there somewhere or have a `TDelegate` with just a single parameter in its signature. So, the following are convertible because they have an `EventArgs` in their implicit delegate.

    public event NameChangedHandler NameChanged;
    public event EventHandler RollNumberChanged;
    public event EventHandler<AgeChangedEventArgs> AgeChanged;

    public delegate void NameChangedHandler(
                         object sender, 
                         NameChangedEventArgs e);

And this one also can be converted because it has a single `T` in its parameter.

    public event Action<Tuple<string, string>> ClassChanged;

What do I do if I have an event like so:

    public event Action<T1, T2...> ItHappened;

**Comment by bartdesmet** [comment]
Direct use of `Observable.Create` can help here:

```csharp
Observable.Create<?>(observer =>
{
    Action<T1, T2, ...> h = (t1, t2, ...) => observer.OnNext(new ?(t1, t2, ...));
    ItHappened += h;
    return () => ItHappened -= h;
});
```

You'll have to decide what `?` is in the above, which is why we don't provide any facilities out-of-the-box: is it a `Tuple<T1, T2, ...>`, a `ValueTuple<T1, T2, ...>`, something else? We'd end up having to provide overloads for up to N arities, assume `Action<...>` delegates are used, and pick an arbitrary type to bundle the components together in a single object. Given that use of `Create` is not particularly tricky, we rather keep the API surface small-ish and without many arbitrary decision. Traditional event patterns are the ones we support natively to cater for the 99% case.

**Comment by Sathyaish** [comment]
@bartdesmet  Fascinating. Thank you. :-)
