### ISSUE TITLE
Would it be possible to maintain a repo with csproj files instead of xproj files?

### ISSUE THREAD

**Issue by Sathyaish** [Reactive-Extensions/Rx.NET#250]
A day or two ago, I forked a copy of the Rx.NET source and wanted to make changes, but I couldn't open it in my Visual Studio 2015 Community installation because I didn't have Update 3 of Visual Studio. I wasted the whole of yesterday and a lot of today trying to install Update 3 but after a few failed attempts, which cost me over a day and a half, I gave up and restored the old installation of Visual Studio 2015 Community without the update.

As a result, I cannot add to the code and submit pull requests.

Thankfully. I have an old copy of the source that used `csproj` files. But I can't push changes from that copy because that is a dirty one in that I have removed all thread-safety code and all validations from each method such as checks for null arguments and reduced the code down to just what each function does.

So, for example, I've removed all those `do { } while(Interlocked.CompareExchange(oldObserver, newObserver, _observer) != oldObserver);` and replaced them with just a single assignment `_observer = newObserver`. I use this code base to understand what the code is doing.

Would it be possible to maintain another repo that has `csproj` files instead of the `xproj` files?

**Comment by onovotny** [comment]
Hi @Sathyaish, I'm sorry, but we don't currently have the time to maintain a separate repo that has `csproj` files. Csproj files today are not able to correctly build this solution because of all of the cross-compiling we're doing; any attempt to do so would result in a huge amount of complexity.

Given the current roadmap of msbuild and the xproj->csproj migration, along with bringing cross-compile support to csproj in a clean way, we're going to wait for that. Once there's a working cross-compiling csproj support, we'll move over to that.

Sorry,
Oren

**Comment by Sathyaish** [comment]
Thanks, @onovotny. That's understandable. I'll give the VS update another shot later tonight.
