### ISSUE TITLE
System.Reactive (3.1.0) forces dependency on NETStandard.Library 

### ISSUE THREAD

**Issue by mot256** [Reactive-Extensions/Rx.NET#295]
I am not sure if that is the intention, but we cannot use System.Reactive (3.1.0) in .NET 4.5
There seems to be a dependency on NETStandard.Library.1.6.0 and other .NETCore libraries.

![image](https://cloud.githubusercontent.com/assets/5630006/20306763/bbdee5c0-ab44-11e6-890b-936f53767387.png)

Is there a way we can install 3.1.0 without these dependencies? Or are we stuck with 3.0.0?

**Comment by suddenelfilio** [comment]
+1

**Comment by Mike-EEE** [comment]
I am also running into an issue w/ 3.1.0.0, where the identity continues to be 3.0.0.0?  Additionally, it appears the dll in .NETStandard is versioned 3.0.1000.0, and the net45 version is 3.0.0.0.  This is not only confusing me greatly, but is confusing my poor tests which are now breaking because of this. 😛  I will rollback until I get more clarity around this.

![](http://content.screencast.com/users/Mike-EEEE/folders/Jing/media/1794ed77-51e0-4371-a698-b2b016911c53/2016-11-16_1028.png)

**Comment by shiftkey** [comment]
cc @onovotny for :eyes:

**Comment by onovotny** [comment]
Two separate issues:

1. Dependency on `NETStandard.Library` for all projects. This was done to ensure all referenced assemblies are correctly unified against all of the framework versions. It's possible that the `net4x` versions may be able to do without that and we can investigate that for the next release. In the interim, that should not block anything as using `NETStandard.Library` is fully supported for `net45`. My recommendation would be to use `project.json` for your NuGet packages instead of `packages.config` as it provides a huge number of benefits, including transitive dependencies. My blog shows you how: https://oren.codes/2016/02/08/project-json-all-the-things/ and there's a converter add-in here: https://marketplace.visualstudio.com/items?itemName=TaylorSouthwickMSFT.NuGetPackagetoProjectjsonConverter

2. Version numbers. Those are correct as per #205. You can see the logic implemented in the `GlobalAssemblyVersion.cs` file in `Ix.NET\Source`. `System.Interactive` cross-compiles for `netstandard1.0` and `net45`. Thus, a desktop .NET app will see a `3.0.1000.0` version while other project types will see the `3.0.0.0` version. This is inline with the API versioning mentioned in #205 discussion. For desktop .NET Projects, the build system should generate binding redirects automatically that unify this.

**Comment by Mike-EEE** [comment]
Ahhh thank you @onovotny for the explanation!  I am using NuGet3 which doesn't generate those redirects, unfortunately (captured in https://github.com/NuGet/Home/issues/3372 please upvote :) ).  I will get in the habit of installing a package in an empty class library (NuGetv2 ) and see if it generates anything there before dropping complaints in a repo. 😄

**Comment by onovotny** [comment]
@Mike-EEE For the binding redirects, it should not be NuGet that's doing it...it's done as part of the build now.

For older projects, they may not have `AutoGenerateBindingRedirects` set though:

https://msdn.microsoft.com/en-us/library/2fc472t2(v=vs.110).aspx

**Comment by onovotny** [comment]
We can fix this for desktop .NET for Ix and Rx. Note that for all other platforms, the full `NETStandard.Library` references will still be needed.

**Comment by Mike-EEE** [comment]
Ah @onovotny I have another layer of complexity in my solution that might be causing my problems in this case.  That is, I am running [PostSharp](https://www.postsharp.net/) and it runs in its own AppDomain during build.  It also does not yet support NuGet3.0 so it requires specific configuration to work property.  After a bunch of trial and error I was able to get everything configured and working properly again. 👍

**Comment by onovotny** [comment]
@Mike-EEE Can you please try the latest 3.1.1 version from the CI feed (https://dotnet.myget.org/gallery/rx) and confirm it works as expected for you?

We can get this tagged and pushed publically very soon.

**Comment by Mike-EEE** [comment]
Ah, I didn't see the build number until now, @onovotny.  I was able to install 00002, but that doesn't have any assemblies.  It is also the only build that is available when I connect to that feed (and when [I view it here](https://dotnet.myget.org/gallery/rx#connectToFeed)).  Is there another location I should be looking at, perhaps?  Or maybe a permissions issue?

**Comment by krs500** [comment]
@onovotny Just tried, System.Reactive 3.1.1-build-00002 still pulls the whole .NET Standard with it. I suspect that's because System.Reactive.Interfaces is still NETStandard.Library-only.

**Comment by onovotny** [comment]
Please look at `00006`. MyGet's indexing was being slow, should be showing up now.

**Comment by krs500** [comment]
@onovotny Tried `00006`. Now it's much better, but `System.Reactive` still tries to pull some extra packages:
![image](https://cloud.githubusercontent.com/assets/1933456/20465821/67f306c4-af6f-11e6-8ed2-f7dd09e064ca.png)

**Comment by onovotny** [comment]
@krs500 Build `00007` should have that addressed if you can give that a shot.

**Comment by krs500** [comment]
@onovotny The build `00007` now installs only what is needed 👍

**Comment by onovotny** [comment]
Great, `3.1.1` is on NuGet now.
