### ISSUE TITLE
Assigning same instance twice to SerialDisposable disposes it

### ISSUE THREAD

**Issue by JohanLarsson** [Reactive-Extensions/Rx.NET#316]
```c#
var disposable = new SerialDisposable();
var foo = new Foo();
disposable.Disposable = foo;
disposable.Disposable = foo; // foo is dead now.
```

This is not an issue for me but I found it a bit surprising when reading the source.

```c#
lock (_gate)
{
    if(ReferenceEquals(value, _current)
        return;
    ...
}
```

Maybe something like ^ makes sense.

**Comment by danielcweber** [comment]
Can you link explicitly to the source?

**Comment by akarnokd** [comment]
It's not in the [current](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/SerialDisposable.cs#L50) source. You may want to use `MultipleAssignmentDisposable` instead.

**Comment by JohanLarsson** [comment]
[Source link](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Core/Reactive/Disposables/SerialDisposable.cs#L41-L66)

The current behavior is not an issue for me other than that it looked like a potential oversight when reading the source.

**Comment by danielcweber** [comment]
I'm afraid I don't quite get it. You read some source code of `SerialDisposable` that checks on reference equality, yet it has since been removed from the current source. Are you using an older binary of Rx and want the old behavior be restored?

**Comment by JohanLarsson** [comment]
I have not seen a check for reference equality anywhere. This thread is a question if it makes sense to add it.

**Comment by bartdesmet** [comment]
I agree it may be surprising but it's not an oversight :-). We intentionally decided not to assign any meaning to instances for any interface types on which we provide an algebra, because it breaks down very quickly. Reference equality checks are shallow by their very nature, so introducing any kind of wrapper will break them (in fact, any observer or disposable "touch" by e.g. `Observer.Create` is subject to wrapping in non-trivial ways).
