### ISSUE TITLE
Which is the last version compatible with Visual Studio 2012 ?

### ISSUE THREAD

**Issue by AnthonyBr** [Reactive-Extensions/Rx.NET#324]
Visual Studio 2012 has nuget version 2.8.60318.667, that is not compatible with Reactive.Extensions 3.1.1.

If copy manually System.Reactive.* packages into the packages directory of my solution, when I launch the package manager from the Visual Studio UI, and I browse for installed package: instead of habing the list of installed package the following error is displayed:

'System.Reactive.Core' already has a dependency defined for 'System.Reactive.Interfaces'.
![nugeterror](https://cloud.githubusercontent.com/assets/6704165/22503430/fd971db0-e871-11e6-80b0-3406cf8b7a8a.png)

If I install package with de package manager command:
install-package System.Reactive
the following error is displayed:
The 'System.Reactive 3.1.1' package requires NuGet client version '2.8.1' or above, but the current NuGet version is '2.8.60318.667'.

**Comment by shiftkey** [comment]
If you cannot use the `System.Reactive.*` packages, as a temporary workaround you can manually install the old `Rx-Main` package from the Package Manager Console (I think this is the right arguments):

```
Install-Package Rx-Main -Version 2.2.5
```

Unfortunately we are unable to support older versions of NuGet, due to the packaging changes required to support .NET Standard.

**Comment by AnthonyBr** [comment]
Thank you, I will be contented with that version. It was installed perfecltly with nuget 2.8.60318.667
