### ISSUE TITLE
Crash even  there is an observable Finally

### ISSUE THREAD

**Issue by wavebit** [Reactive-Extensions/Rx.NET#415]
Hello, 
I am learning Rx following http://introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html
When I try this code below from the tutorial, I found the bug is not fixed. Rx.net version is 3.1.1

var source = new Subject<int>();
var result = source.Finally(() => Console.WriteLine("Finally"));
result.Subscribe(
Console.WriteLine,
//Console.WriteLine,
() => Console.WriteLine("Completed"));
source.OnNext(1);
source.OnNext(2);
source.OnNext(3);
//Brings the app down. Finally action is not called.
source.OnError(new Exception("Fail"));

**Comment by danielcweber** [comment]
That's because you are not observing the OnError-notification (you commented it out). The overload of `Subscribe` you use will just rethrow the exception, thus bringing the app down. Either do something with the exception (log it or whatever) or use `Catch` on `source`. Note that `Finally` will not supress the exception (like in a C#-finally-Block).
