### ISSUE TITLE
Scheduler is hard to use should

### ISSUE THREAD

**Issue by wavebit** [Reactive-Extensions/Rx.NET#434]
Hello
I want to implement a custom scheduler like below, but I always get stack overflow error, it did not work as it seems to be . We have to spend much time to study how to use it. Some other frameworks based on Rx.net always crash on muti-thread and muti-process application . 

  class MyScheduler : IScheduler
  {
    public IDisposable Schedule<TState>(TState state, Func<IScheduler, TState, IDisposable> action)
    {
      action(this, state).Dispose();
      return Disposable.Empty;
    }
    public DateTimeOffset Now { get; }
  }

**Comment by akarnokd** [comment]
There is the `Scheduler.Current` that works with recursive scheduling without going asynchronous.

**Comment by wavebit** [comment]
I just want the observer and subscription work on the same specific thread.

**Comment by bartdesmet** [comment]
Can you elaborate on this?

> Some other frameworks based on Rx.net always crash on muti-thread and muti-process application.

If that's the root cause leading you to build your own scheduler, we should look into what's causing grief there. If you still need to implement your own scheduler, consider inheriting from `LocalScheduler`. If you need thread-affinity, you can use `EventLoopScheduler` to have a dedicated thread; for other threads (which already exist so you can't create one yourself), the use of `Scheduler.Current` is advised; this will install a trampoline on the current thread to bounce all work onto.

**Comment by wavebit** [comment]
"Some other frameworks based on Rx.net always crash on muti-thread and muti-process application."
I means this https://github.com/clariuslabs/reactivesockets, if I run two clients progresses at the same computer, the received data is incorrect, then the application crash.
Sorry, I have stopped learning Rx.net, it is hard to understand, and sometimes the API does not work as it is thought #417
